---
- name: Help INFO (-e help=true)
  pause:
    echo: yes
    prompt: |
      NAME
        configure_interfaces

      DESCRIPTION
        Role to configure addresses for multiple interfaces

      STEPS
        1) Add interfaces IP
        2) Get all interfaces
        3) Delete missing IP addresses from interfaces (default configure_interfaces_delete_missing=false)
        4) Commit changes

      EXAMPLES
        ansible-playbook -i [...] playbooks/ansible_collections/base/configure_interfaces.yml
        ansible-playbook -i [...] playbooks/ansible_collections/base/configure_interfaces.yml -e configure_interfaces_delete_missing=True //delete IP address from interfaces which are missing in the inventory
        ansible-playbook -i [...] playbooks/ansible_collections/base/configure_interfaces.yml -e label=1.1 //only configure interface with corresponding label
        ansible-playbook -i [...] playbooks/ansible_collections/base/configure_interfaces.yml -e address=192.168.42.110 //only configure interface with corresponding label
        ansible-playbook -i [...] playbooks/ansible_collections/base/configure_interfaces.yml -e address=192.168.42.113 -e configure_interfaces_delete_missing=True //only delete one IP from interface if not contained in inventory
        ansible-playbook -i [...] playbooks/ansible_collections/base/configure_interfaces.yml -e label=1.1 -e configure_interfaces_delete_missing=True //clean up only one interface

      INVENTORY
      ==========
      # configure IP addresses for interfaces
      # recommended host based configuration (in hosts_vars/<< host_name >>.yml; host_name from hosts file)
      interfaces:
        - label: '1.1'
          addresses:
            - address: "192.168.42.110"
              maskOrPrefix: "24"
              allowManagement: true
              enabled: true
            - address: "192.168.42.111"
              maskOrPrefix: "24"
              allowManagement: false
              enabled: true
      ==========

      INTERACTION
        ENTER         = continue
        Ctrl+C + 'C'  = continue
        Ctrl+C + 'A'  = abort
  when: help is defined
- name: Add interfaces IP
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: "ibmsecurity.isam.base.network.{{ configure_interfaces_action }}.add"
    isamapi:
      label: "{{ item.0.label }}"
      address: "{{ item.1.address }}"
      maskOrPrefix: "{{ item.1.maskOrPrefix }}"
      allowManagement: "{{ item.1.allowManagement }}"
      overrideSubnetChecking: "{{ item.1.overrideSubnetChecking | default(False) }}"
      enabled: "{{ item.1.enabled | default(False) }}"
  when: item.0.label == label and item.1.address == address
  loop: "{{ interfaces | subelements('addresses', {'skip_missing': True}) }}"
  loop_control:
    label: "Processing interface {{ item.0.label }} and IP address {{ item.1.address }}"
  notify: Commit Changes

- name: Get all interfaces
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.network.interfaces.get_all
  when: configure_interfaces_delete_missing
  register: ret_obj

- vars:
    filter_current_interfaces: "interfaces[].{label: label,addresses: ipv4.addresses[].address}"
  set_fact:
    addresses_list_server: "{{ ret_obj.data | json_query(filter_current_interfaces) }}"
  when: ret_obj.data is defined and ret_obj.data != []

- vars:
    filter_current_interfaces: "[? label=='{{ item.0.label }}'].addresses[].address"
  name: Delete missing IP addresses from interfaces (-e configure_interfaces_delete_missing=true)
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: "ibmsecurity.isam.base.network.{{ configure_interfaces_action }}.delete"
    isamapi:
      label: "{{ item.0.label }}"
      address: "{{ item.1 }}"
  when: item.1 is not in (interfaces | json_query(filter_current_interfaces)) and configure_interfaces_delete_missing and item.0.label == label and item.1 == address
  with_subelements:
    - "{{ addresses_list_server | default([]) }}"
    - addresses
    - skip_missing: true
  notify: Commit Changes
