---

galaxy_info:
  author: IBM
  description: Role to configure runtime tuning parameters
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - configure
  - runtime_tuning

dependencies:
  - common_handlers
